/*
 * Copyright (C) 2016+ AzerothCore <www.azerothcore.org>, released under GNU AGPL v3 license: https://github.com/azerothcore/azerothcore-wotlk/blob/master/LICENSE-AGPL3
 */

#include "AscensionReaperDirge.h"
#include "AscensionTinkerOverload.h"
#include "AscensionRunemasterGlyphs.h"
#include "AscensionManastorm.h"
#include "AscensionRunemasterBrand.h"
#include "AscensionRunemasterScaling.h"
#include "AscensionTinkerRockadier.h"
#include "AscensionRunemasterZenith.h"
#include "AscensionRunemasterEchoes.h"
#include "AscensionVenomancerVenoms.h"
#include "AscensionVenomancerVenomProcs.h"
#include "AscensionVenomancerVenomTalents.h"
#include "AscensionVenomancerVenomPayloads.h"
#include "AscensionTinkerCombatSymbiosis.h"

void AddAscensionCompatScripts();
void AddAscensionTravelPermitScripts();
void AddSC_AscensionRulesets();
void AddSC_AscensionThreatRedirect();
void AddCoABugReportScripts();
void AddCoAGameplayTestScripts();
void AddAscensionEffectiveSpellReportScripts();
void AddSC_AscensionResourceTalents();
void AddAscensionBarbarianCompletionScripts();
void AddAscensionBarbarianEventScripts();
void AddAscensionBarbarianAbilityScripts();
void AddAscensionGuardianStandardScripts();
void AddAscensionGuardianFavorScripts();
void AddAscensionGuardianEventScripts();
void AddAscensionGuardianCompletionScripts();
void AddAscensionGuardianAbilityScripts();
void AddAscensionGuardianTalentScripts();
void AddAscensionGuardianDrumScripts();
void AddAscensionRangerDamageScripts();
void AddAscensionRangerScalingScripts();
void AddAscensionRangerAssaultScripts();
void AddAscensionWitchHunterTonicScripts();
void AddAscensionWitchHunterTonicTalentScripts();
void AddAscensionWitchHunterTorchScripts();
void AddAscensionWitchHunterFlameScripts();
void AddAscensionWitchHunterTorchlightScripts();
void AddAscensionWitchHunterStakeScripts();
void AddAscensionWitchHunterCompletionScripts();
void AddAscensionWitchHunterEventScripts();
void AddAscensionWitchHunterAbilityScripts();
void AddAscensionWitchHunterDefenseScripts();
void AddAscensionWitchHunterSummonScripts();
void AddAscensionWitchDoctorCompletionScripts();
void AddAscensionWitchDoctorEventScripts();
void AddAscensionWitchDoctorAbilityScripts();
void AddAscensionWitchDoctorBrewingScripts();
void AddAscensionWitchDoctorAuraScripts();
void AddAscensionWitchDoctorSummonScripts();
void AddAscensionNecromancerScripts();
void AddAscensionNecromancerContractScripts();
void AddAscensionNecromancerSummonScripts();
void AddAscensionNecromancerEventScripts();
void AddAscensionNecromancerAbilityScripts();
void AddAscensionNecromancerAuraScripts();
void AddSC_AscensionXoroth();
void AddSC_AscensionStarcaller();
void AddSC_AscensionStarcallerContracts();
void AddSC_AscensionPyromancer();
void AddSC_AscensionPyromancerContracts();
void AddSC_AscensionPyromancerEvents();
void AddSC_AscensionPyromancerAbilities();
void AddSC_AscensionPyromancerAuras();
void AddSC_AscensionPyromancerSummons();
void AddSC_AscensionCultist();
void AddSC_AscensionCultistContracts();
void AddSC_AscensionCultistEvents();
void AddSC_AscensionCultistAbilities();
void AddSC_AscensionCultistAuras();
void AddSC_AscensionCultistSummons();
void AddSC_AscensionVenomancer();
void AddSC_AscensionVenomancerContracts();
void AddSC_AscensionVenomancerEvents();
void AddSC_AscensionVenomancerAbilities();
void AddSC_AscensionVenomancerAuras();
void AddSC_AscensionVenomancerSummons();
void AddSC_AscensionTinker();
void AddSC_AscensionTinkerContracts();
void AddSC_AscensionTinkerEvents();
void AddSC_AscensionTinkerAbilities();
void AddSC_AscensionTinkerAuras();
void AddSC_AscensionTinkerSummons();
void AddSC_AscensionSunCleric();
void AddSC_AscensionSunClericContracts();
void AddSC_AscensionSunClericEvents();
void AddSC_AscensionSunClericAbilities();
void AddSC_AscensionSunClericAuras();
void AddSC_AscensionSunClericSummons();
void AddSC_AscensionStarcallerEvents();
void AddSC_AscensionStarcallerAbilities();
void AddSC_AscensionStarcallerAuras();
void AddSC_AscensionStarcallerMechanics();
void AddSC_AscensionXorothContracts();
void AddSC_AscensionXorothEvents();
void AddSC_AscensionXorothAbilities();
void AddSC_AscensionXorothAuras();
void AddSC_AscensionXorothSummons();
void AddSC_AscensionFelsworn();
void AddSC_AscensionFelswornContracts();
void AddSC_AscensionFelswornAuras();
void AddSC_AscensionFelswornEvents();
void AddSC_AscensionFelswornAbilities();
void AddSC_AscensionFelswornSummons();
void AddSC_AscensionTemplar();
void AddSC_AscensionTemplarContracts();
void AddSC_AscensionTemplarAuras();
void AddSC_AscensionTemplarEvents();
void AddSC_AscensionTemplarAbilities();
void AddSC_AscensionTemplarSummons();
void AddSC_AscensionTemplarTemporaryLibramProcs();
void AddAscensionTinkerAugmentationScripts();
void AddAscensionTinkerAugmentationTalentScripts();
void AddAscensionTinkerHackingScripts();
void AddSC_AscensionPrimalistEarthshaping();
void AddSC_AscensionVenomancerCatalyst();
void AddSC_AscensionPrimalistSpiritBeast();
void AddSC_AscensionPrimalistWeapons();
void AddSC_AscensionPrimalistTalents();
void AddSC_AscensionRunemasterTalents();
void AddSC_AscensionRunemasterTravel();
void AddSC_AscensionStormbringerTalents();
void AddSC_AscensionStormbringerWindGate();
void AddSC_AscensionStormbringerZephyr();
void AddSC_AscensionStormbringerPet();
void AddSC_AscensionStormbringerSphere();
void AddSC_AscensionBloodmageSecondary();
void AddSC_AscensionBloodmageHemostasis();
void AddSC_AscensionRangerSecondary();
void AddSC_AscensionRangerDirtyFighter();
void AddSC_AscensionRangerHookshot();
void AddSC_AscensionRangerOutmaneuver();
void AddSC_AscensionRunemasterManuscription();
void AddSC_AscensionRangerTalents();
void AddSC_AscensionRangerFlowers();
void AddSC_AscensionRangerPetalkeeper();
void AddSC_AscensionRangerFalconstrike();
void AddSC_AscensionChronomancerTalents();
void AddSC_AscensionChronomancerTime();
void AddSC_AscensionChronomancerMovement();
void AddSC_AscensionAdventurerCache();
void AddSC_AscensionBankVoucher();
void AddSC_AscensionPersonalBank();
void AddSC_AscensionBloodmageTalents();
void AddSC_AscensionBloodmageVitality();
void AddSC_AscensionReaperReflexes();
void AddSC_AscensionPrimalistMountain();
void AddSC_AscensionChronomancerRipple();
void AddSC_AscensionChronomancerSecondary();
void AddSC_AscensionVenomancerSerpentFang();
void AddSC_AscensionSunClericBattleCleric();
void AddSC_AscensionReaperTalents();
void AddSC_AscensionReaperSecondary();
void AddSC_AscensionPrimalistSecondary();
void AddSC_AscensionRunemasterSecondary();
void AddSC_AscensionRunemasterHurricane();
void AddSC_AscensionRunemasterRiftClones();

// Add all
// cf. the naming convention https://github.com/azerothcore/azerothcore-wotlk/blob/master/doc/changelog/master.md#how-to-upgrade-4
// additionally replace all '-' in the module folder name with '_' here
void Addmod_ascension_compatScripts()
{
    AddAscensionManastormScripts();
    AddSC_AscensionReaperDirge();
    AddAscensionTinkerOverloadScripts();
    AddAscensionCompatScripts();
    AddAscensionTravelPermitScripts();
    AddAscensionBarbarianCompletionScripts();
    AddAscensionBarbarianEventScripts();
    AddAscensionBarbarianAbilityScripts();
    AddAscensionGuardianStandardScripts();
    AddAscensionGuardianFavorScripts();
    AddAscensionGuardianEventScripts();
    AddAscensionGuardianCompletionScripts();
    AddAscensionGuardianAbilityScripts();
    AddAscensionGuardianTalentScripts();
    AddAscensionGuardianDrumScripts();
    AddAscensionRangerDamageScripts();
    AddAscensionRangerScalingScripts();
    AddAscensionRangerAssaultScripts();
    AddAscensionWitchHunterTonicScripts();
    AddAscensionWitchHunterTonicTalentScripts();
    AddAscensionWitchHunterTorchScripts();
    AddAscensionWitchHunterFlameScripts();
    AddAscensionWitchHunterTorchlightScripts();
    AddAscensionWitchHunterStakeScripts();
    AddAscensionWitchHunterCompletionScripts();
    AddAscensionWitchHunterEventScripts();
    AddAscensionWitchHunterAbilityScripts();
    AddAscensionWitchHunterDefenseScripts();
    AddAscensionWitchHunterSummonScripts();
    AddAscensionWitchDoctorCompletionScripts();
    AddAscensionWitchDoctorEventScripts();
    AddAscensionWitchDoctorAbilityScripts();
    AddAscensionWitchDoctorBrewingScripts();
    AddAscensionWitchDoctorAuraScripts();
    AddAscensionWitchDoctorSummonScripts();
    AddAscensionNecromancerScripts();
    AddAscensionNecromancerContractScripts();
    AddAscensionNecromancerSummonScripts();
    AddAscensionNecromancerEventScripts();
    AddAscensionNecromancerAbilityScripts();
    AddAscensionNecromancerAuraScripts();
    AddSC_AscensionXoroth();
    AddSC_AscensionStarcaller();
    AddSC_AscensionStarcallerContracts();
    AddSC_AscensionPyromancer();
    AddSC_AscensionPyromancerContracts();
    AddSC_AscensionPyromancerEvents();
    AddSC_AscensionPyromancerAbilities();
    AddSC_AscensionPyromancerAuras();
    AddSC_AscensionPyromancerSummons();
    AddSC_AscensionCultist();
    AddSC_AscensionCultistContracts();
    AddSC_AscensionCultistEvents();
    AddSC_AscensionCultistAbilities();
    AddSC_AscensionCultistAuras();
    AddSC_AscensionCultistSummons();
    AddSC_AscensionVenomancer();
    AddSC_AscensionVenomancerContracts();
    AddSC_AscensionVenomancerEvents();
    AddSC_AscensionVenomancerAbilities();
    AddSC_AscensionVenomancerAuras();
    AddSC_AscensionVenomancerSummons();
    AddSC_AscensionTinker();
    AddSC_AscensionTinkerContracts();
    AddSC_AscensionTinkerEvents();
    AddSC_AscensionTinkerAbilities();
    AddSC_AscensionTinkerAuras();
    AddSC_AscensionTinkerSummons();
    AddSC_AscensionSunCleric();
    AddSC_AscensionSunClericContracts();
    AddSC_AscensionSunClericEvents();
    AddSC_AscensionSunClericAbilities();
    AddSC_AscensionSunClericAuras();
    AddSC_AscensionSunClericSummons();
    AddSC_AscensionStarcallerEvents();
    AddSC_AscensionStarcallerAbilities();
    AddSC_AscensionStarcallerAuras();
    AddSC_AscensionStarcallerMechanics();
    AddSC_AscensionXorothContracts();
    AddSC_AscensionXorothEvents();
    AddSC_AscensionXorothAbilities();
    AddSC_AscensionXorothAuras();
    AddSC_AscensionXorothSummons();
    AddSC_AscensionFelsworn();
    AddSC_AscensionFelswornContracts();
    AddSC_AscensionFelswornAuras();
    AddSC_AscensionFelswornEvents();
    AddSC_AscensionFelswornAbilities();
    AddSC_AscensionFelswornSummons();
    AddSC_AscensionTemplar();
    AddSC_AscensionTemplarContracts();
    AddSC_AscensionTemplarAuras();
    AddSC_AscensionTemplarEvents();
    AddSC_AscensionTemplarAbilities();
    AddSC_AscensionTemplarSummons();
    AddSC_AscensionTemplarTemporaryLibramProcs();
    AddAscensionTinkerAugmentationScripts();
    AddAscensionTinkerAugmentationTalentScripts();
    AddAscensionTinkerHackingScripts();
    AddSC_AscensionPrimalistEarthshaping();
    AddAscensionRunemasterGlyphScripts();
    AddSC_AscensionVenomancerCatalyst();
    AddAscensionRunemasterBrandScripts();
    AddAscensionRunemasterScalingScripts();
    AddAscensionTinkerRockadierScripts();
    AddSC_AscensionPrimalistSpiritBeast();
    AddSC_AscensionPrimalistWeapons();
    AddSC_AscensionPrimalistTalents();
    AddSC_AscensionRunemasterTalents();
    AddSC_AscensionRunemasterTravel();
    AddSC_AscensionStormbringerTalents();
    AddSC_AscensionStormbringerWindGate();
    AddSC_AscensionStormbringerZephyr();
    AddSC_AscensionStormbringerPet();
    AddSC_AscensionStormbringerSphere();
    AddSC_AscensionBloodmageSecondary();
    AddSC_AscensionBloodmageHemostasis();
    AddSC_AscensionRangerSecondary();
    AddSC_AscensionRangerDirtyFighter();
    AddSC_AscensionRangerHookshot();
    AddSC_AscensionRangerOutmaneuver();
    AddSC_AscensionRunemasterManuscription();
    AddSC_AscensionRangerTalents();
    AddSC_AscensionRangerFlowers();
    AddSC_AscensionRangerPetalkeeper();
    AddSC_AscensionRangerFalconstrike();
    AddSC_AscensionChronomancerTalents();
    AddSC_AscensionChronomancerTime();
    AddSC_AscensionChronomancerMovement();
    AddSC_AscensionAdventurerCache();
    AddSC_AscensionBankVoucher();
    AddSC_AscensionPersonalBank();
    AddSC_AscensionBloodmageTalents();
    AddSC_AscensionBloodmageVitality();
    AddSC_AscensionReaperReflexes();
    AddSC_AscensionPrimalistMountain();
    AddSC_AscensionChronomancerRipple();
    AddSC_AscensionChronomancerSecondary();
    AddSC_AscensionVenomancerSerpentFang();
    AddSC_AscensionSunClericBattleCleric();
    AddSC_AscensionReaperTalents();
    AddSC_AscensionReaperSecondary();
    AddSC_AscensionPrimalistSecondary();
    AddSC_AscensionRunemasterSecondary();
    AddSC_AscensionRunemasterHurricane();
    AddSC_AscensionRunemasterRiftClones();
    AddAscensionRunemasterZenithScripts();
    AddAscensionRunemasterEchoesScripts();
    AddAscensionVenomancerVenomScripts();
    AddAscensionVenomancerVenomProcScripts();
    AddAscensionVenomancerVenomTalentScripts();
    AddAscensionVenomancerVenomPayloadScripts();
    AddAscensionTinkerCombatSymbiosisScripts();
    AddCoABugReportScripts();
    AddCoAGameplayTestScripts();
    AddAscensionEffectiveSpellReportScripts();
    AddSC_AscensionResourceTalents();
    AddSC_AscensionRulesets();
    AddSC_AscensionThreatRedirect();
}
